"""Model and environment tests for the dual-arm (lkwy73_o1) task.

The asset is generated by ``tools/build_dual_arm_model.py``; these tests pin the
properties the environments rely on, so a regenerated asset cannot silently
lose an actuator, gain a CAD self-contact, unpin the fingers or break the
mirror relation between the two arms.
"""

import mujoco
import numpy as np
import pytest

from env import env_names, make_env
from env.dual_arm_reacher import (
    DualArmCoopReach,
    DualArmReach,
    mirror_safe_limits,
)
from paths import asset_path

MODEL_PATH = asset_path("dual_arm_reach.xml")
DUAL_ENVS = ("dual_arm_reach", "dual_arm_coop")
#: 36 DoF in the model, 14 of them actuated (7 per arm).
EXPECTED_OBS = 60
EXPECTED_ACTIONS = 14


@pytest.fixture(scope="module")
def model():
    return mujoco.MjModel.from_xml_path(MODEL_PATH)


def test_model_wiring(model):
    assert model.nu == EXPECTED_ACTIONS
    assert model.nmocap == 2, "one mocap target per arm"
    assert model.nq == model.nv == 36, "36 hinge joints, fingers included"
    assert [mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_SITE, i)
            for i in range(model.nsite)].count("tip_left") == 1
    assert mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "tip_right") >= 0
    # the decimated meshes must stay under MuJoCo's 200k-face STL limit
    assert model.mesh_facenum.max() < 200_000
    # 11.11 kg: base + 2 arms + 2 hands, as in the source URDF
    assert model.body_mass.sum() == pytest.approx(11.11, abs=0.01)


def test_cad_self_contacts_are_excluded(model):
    """L1/base and L5/L7 overlap in the CAD; the asset must exclude them."""
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)
    assert data.ncon == 0


def test_fingers_stay_pinned(model):
    """The 22 finger joints are held by equality constraints at q = 0."""
    data = mujoco.MjData(model)
    for _ in range(300):
        mujoco.mj_step(model, data)
    fingers = [
        data.qpos[model.jnt_qposadr[joint]]
        for joint in range(model.njnt)
        if (mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, joint) or "")
        .startswith(("lh_", "rh_"))
    ]
    assert len(fingers) == 22
    assert np.abs(fingers).max() < 1e-3


def test_registry_exposes_the_dual_arm_tasks():
    names = set(env_names())
    assert set(DUAL_ENVS) <= names


@pytest.mark.parametrize("name", DUAL_ENVS)
def test_spaces_and_step(name):
    env = make_env(name)
    try:
        assert env.observation_space.shape == (EXPECTED_OBS,)
        assert env.action_space.shape == (EXPECTED_ACTIONS,)
        obs, info = env.reset(seed=0)
        assert obs.shape == (EXPECTED_OBS,)
        assert obs.dtype == np.float32
        assert np.all(np.isfinite(obs))
        assert info["steps"] == 0
        assert set(("dist_left", "dist_right", "targets")) <= set(info)

        obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
        assert obs.shape == (EXPECTED_OBS,)
        assert np.isfinite(reward)
        assert isinstance(terminated, (bool, np.bool_))
        assert isinstance(truncated, (bool, np.bool_))
        assert info["steps"] == 1
    finally:
        env.close()


@pytest.mark.parametrize("name", DUAL_ENVS)
def test_reset_is_reproducible_and_not_trivial(name):
    env = make_env(name)
    try:
        obs_a, _ = env.reset(seed=7)
        targets_a = env.targets.copy()
        obs_b, _ = env.reset(seed=7)
        assert np.allclose(obs_a, obs_b)
        assert np.allclose(targets_a, env.targets)
        # 200 resets: no episode may start inside the success radius, which is
        # what MIN_START_DIST is for.
        for seed in range(40):
            env.reset(seed=seed)
            dists = [env.arm_dist(i) for i in range(2)]
            assert min(dists) >= DualArmReach.MIN_START_DIST - 1e-9
    finally:
        env.close()


def test_episode_terminates_when_both_arms_arrive():
    env = make_env("dual_arm_reach")
    try:
        env.reset(seed=0)
        env.data.qvel[:] = 0.0
        # put each target on its own tip: the task is now solved
        env._targets = env.tips.copy()
        reward, terminated = env._compute_reward(np.zeros(env.n_dof))
        assert terminated is True
        assert reward >= env.success_reward
        assert env._get_info()["success"] is True
        # One arm alone must not terminate the episode.  Clear the latch first:
        # arriving is sticky in this env (see test_latched_vs_simultaneous_success).
        env._arm_done[:] = False
        env._targets[0] = env.tips[0].copy()
        env._targets[1] = env.tips[1] + np.array([1.0, 0.0, 0.0])
        _, terminated = env._compute_reward(np.zeros(env.n_dof))
        assert terminated is False
    finally:
        env.close()


def test_single_arm_arrival_is_paid_once():
    """Multi-arm credit assignment: each arm pays a one-off bonus, not a stream."""
    env = make_env("dual_arm_reach")
    try:
        env.reset(seed=0)
        env.data.qvel[:] = 0.0
        env._targets[0] = env.tips[0].copy()
        env._targets[1] = env.tips[1].copy() + np.array([0.8, 0.0, 0.0])
        zeros = np.zeros(env.n_dof)

        first, terminated = env._compute_reward(zeros)
        assert terminated is False
        assert list(env._arm_done) == [True, False]
        second, _ = env._compute_reward(zeros)
        # the second call still holds the same geometry, so the difference is
        # exactly the one-off bonus that must not be paid twice
        assert first - second == pytest.approx(env.arm_success_reward)
        # and both arms arriving pays the full success bonus on top
        env._targets[1] = env.tips[1].copy()
        env._arm_done[:] = False
        third, terminated = env._compute_reward(zeros)
        assert terminated is True
        assert third >= env.success_reward
    finally:
        env.close()


def test_latched_vs_simultaneous_success():
    """``dual_arm_reach`` latches arrivals, ``dual_arm_coop`` must hold the bar."""
    zeros = np.zeros(EXPECTED_ACTIONS)
    for name, latched in (("dual_arm_reach", True), ("dual_arm_coop", False)):
        env = make_env(name)
        try:
            env.reset(seed=3)
            env.data.qvel[:] = 0.0
            # arm 0 arrives, then leaves; arm 1 arrives afterwards
            env._targets[0] = env.tips[0].copy()
            env._targets[1] = env.tips[1].copy() + np.array([0.9, 0.0, 0.0])
            _, terminated = env._compute_reward(zeros)
            assert terminated is False
            env._targets[0] = env.tips[0].copy() + np.array([0.5, 0.0, 0.0])
            env._targets[1] = env.tips[1].copy()
            _, terminated = env._compute_reward(zeros)
            assert terminated is latched, f"{name}: latched={latched}"
            if not latched:
                # the cooperative task additionally needs a matching bar
                env._targets = env.tips.copy()
                _, terminated = env._compute_reward(zeros)
                assert terminated is True
        finally:
            env.close()


def test_mirror_signs_reproduce_the_other_arm():
    """The documented mirror map must map the left arm onto the right arm."""
    env = make_env("dual_arm_reach")
    try:
        env.reset(seed=0)
        signs = np.asarray(DualArmCoopReach.MIRROR_SIGNS)
        left_limits, right_limits = env._limits
        # sample only where the mirrored pose also respects the right limits
        low, high = mirror_safe_limits(left_limits, right_limits, signs)
        assert np.all(low <= high), "the arms share no mirrored joint range"
        rng = np.random.default_rng(0)
        worst = 0.0
        for _ in range(40):
            q_left = rng.uniform(low, high)
            q_right = signs * q_left
            env.data.qpos[env._qpos_idx[0]] = q_left
            env.data.qpos[env._qpos_idx[1]] = q_right
            mujoco.mj_kinematics(env.model, env.data)
            tips = env.tips
            mirrored = tips[0].copy()
            mirrored[1] *= -1  # reflect through the y = 0 symmetry plane
            worst = max(worst, float(np.linalg.norm(mirrored - tips[1])))
        # ~5 mm is the residual asymmetry of the two CAD arm parts
        assert worst < 0.015, f"mirror mismatch {worst * 1000:.1f} mm"
    finally:
        env.close()


def test_coop_targets_are_jointly_achievable():
    """The bar is built from a pose pair the two arms can actually hold."""
    env = make_env("dual_arm_coop")
    try:
        worst_reachable = 0.0
        worst_offset = 0.0
        for seed in range(20):
            env.reset(seed=seed)
            env.data.qpos[env._qpos_idx[0]] = env.reference_pose[0]
            env.data.qpos[env._qpos_idx[1]] = env.reference_pose[1]
            mujoco.mj_kinematics(env.model, env.data)
            worst_reachable = max(
                worst_reachable, float(np.abs(env.tips - env.achievable_pair).max())
            )
            offset = np.linalg.norm(env.targets - env.achievable_pair, axis=1).max()
            worst_offset = max(worst_offset, float(offset))
            bar = float(np.linalg.norm(env.targets[1] - env.targets[0]))
            assert DualArmCoopReach.BAR_MIN - 0.1 <= bar <= DualArmCoopReach.BAR_MAX + 0.1
        # the reference pose lands on the achievable pair (jitter is 2 cm)
        assert worst_reachable < 0.05
        # and the rigid transform stays small relative to the arm length
        assert worst_offset < 0.25
    finally:
        env.close()


def test_coop_rewards_coordination():
    """Breaking the bar length must cost reward even with the tips unchanged."""
    env = make_env("dual_arm_coop")
    try:
        env.reset(seed=0)
        # tips exactly on their targets -> a perfect bar -> no penalty
        env._targets = env.tips.copy()
        assert env._coordination_reward() == pytest.approx(0.0, abs=1e-9)
        # stretch one end by 30 cm -> the bar is broken and must cost reward
        env._targets[1] = env._targets[1] + np.array([0.0, 0.3, 0.0])
        assert env._coordination_reward() == pytest.approx(
            -env.PAIR_COST * 0.3, rel=1e-3
        )
        assert env._get_info()["bar_error"] == pytest.approx(0.3, rel=1e-3)
    finally:
        env.close()


def test_rendering_produces_frames():
    env = make_env("dual_arm_reach", render_mode="rgb_array")
    try:
        env.reset(seed=0)
        frame = env.render()
        assert frame.ndim == 3 and frame.shape[2] == 3
        assert frame.dtype == np.uint8
    finally:
        env.close()
